import os
import pyodbc
import pandas as pd
import gspread
import logging
import numpy as np

from google.oauth2.service_account import Credentials
from dotenv import load_dotenv
from datetime import datetime

from monitor import run_with_monitor  # type: ignore # noqa: E402

# ===============================
# LOGGING
# ===============================
logging.basicConfig(
    filename="faltasTT.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)

# ===============================
# LOAD ENV
# ===============================
load_dotenv()
# ===============================
# CONFIGURAÇÕES GOOGLE
# ===============================
SERVICE_ACCOUNT_FILE = "/app/credentials.json"
SPREADSHEET_ID = "12c9hVVnWg48YKxxX8b2v9nBB8Mo5f8x7R9vWfC5FUa0"
WORKSHEET_NAME = "OCORRENCIAS"

# ===============================
# PLANILHA DE LOG
# ===============================
LOG_SPREADSHEET_ID = "1Q1LjFhquJs6U0NccUo1HJzqzQ9TNlYl-7cdOFYRIMTA"
LOG_WORKSHEET_NAME = "API-OCORRENCIAS"

# ===============================
# CONEXÃO SQL SERVER
# ===============================


def conectar_bd():
    conn_str = (
        "DRIVER={ODBC Driver 17 for SQL Server};"
        f"SERVER={os.getenv('DB_SERVER')};"
        f"DATABASE={os.getenv('DB_DATABASE')};"
        f"UID={os.getenv('DB_USER')};"
        f"PWD={os.getenv('DB_PASSWORD')};"
        "TrustServerCertificate=yes;"
    )
    return pyodbc.connect(conn_str, timeout=30)

# ===============================
# QUERY
# ===============================


QUERY = """
WITH RELFUNC_FIX AS (
    SELECT *
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY RELACAOENTIDADE
                   ORDER BY CODIGO DESC
               ) AS RN
        FROM RELACAOENTIDADE
        WHERE CODIGO IS NOT NULL
    ) X
    WHERE RN = 1
),

BASE_EVENTOS AS (

/* =========================
   FALTAS
========================= */
SELECT
    PONTO.DATA AS DATA,
    RELFUNC.CODIGO AS RE,
    ENTFUNC.NOMERESUMIDO AS FUNCIONARIO,

    CASE
        WHEN COALESCE(PONTO.TPABONOPONTO, 1) = 1 THEN 'FALTA INJUSTIFICADA'
        WHEN PONTO.TPABONOPONTO IN (2, 3) THEN 'FALTA ABONADA'
    END AS TIPO_EVENTO,

    ENTEMP.NOMERESUMIDO AS EMPRESA,
    ENTBASE.NOMERESUMIDO AS BASEOPERACIONAL,
    ENTCLI.NOMERESUMIDO AS CLIENTE,
    ENTLOCAL.NOMERESUMIDO AS LOCALSERVICO,
    ENTAREA.NOMECOMPLETO AS AREASUPERVISAO,
    TURNOTRABALHO.DESCRICAO AS TURNO,
    CARGO.DESCRICAO AS CARGO

FROM PONTO

INNER JOIN RELFUNC_FIX RELFUNC
    ON RELFUNC.RELACAOENTIDADE = PONTO.COLABORADOR

INNER JOIN ENTIDADE ENTFUNC
    ON ENTFUNC.ENTIDADE = RELFUNC.PAPEL1

OUTER APPLY (
    SELECT TOP 1 CF.*
    FROM CARGOFUNCIONARIOS CF
    WHERE CF.FUNCIONARIO = PONTO.COLABORADOR
      AND CF.DTINICIO <= PONTO.DATA
      AND (CF.DTFIM >= PONTO.DATA OR CF.DTFIM IS NULL)
    ORDER BY CF.DTINICIO DESC
) CF_REF

INNER JOIN CARGO
    ON CF_REF.CARGO = CARGO.CARGO

INNER JOIN VAGAITEMCONTRATO VAGA
    ON PONTO.VAGAITEMCONTRATO = VAGA.VAGAITEMCONTRATO

INNER JOIN TURNOTRABALHO
    ON VAGA.TURNOTRABALHO = TURNOTRABALHO.TURNOTRABALHO

INNER JOIN POSTOLOCALSERVICO
    ON POSTOLOCALSERVICO.POSTOLOCALSERVICO = VAGA.POSTOLOCALSERVICO

INNER JOIN LOCALSERVICOEMP
    ON LOCALSERVICOEMP.LOCALSERVICOEMP = POSTOLOCALSERVICO.LOCALSERVICOEMP

INNER JOIN RELACAOENTIDADE RELEMP
    ON RELEMP.RELACAOENTIDADE = LOCALSERVICOEMP.EMPRESA

INNER JOIN ENTIDADE ENTEMP
    ON ENTEMP.ENTIDADE = RELEMP.PAPEL1

INNER JOIN LOCALSERVICO
    ON LOCALSERVICO.LOCALSERVICO = LOCALSERVICOEMP.LOCALSERVICO

INNER JOIN RELACAOENTIDADE RELBASE
    ON RELBASE.RELACAOENTIDADE = LOCALSERVICO.BASEOPERACIONAL

INNER JOIN ENTIDADE ENTBASE
    ON ENTBASE.ENTIDADE = RELBASE.PAPEL1

INNER JOIN RELACAOENTIDADE RELLOCAL
    ON RELLOCAL.RELACAOENTIDADE = LOCALSERVICOEMP.LOCALSERVICO

INNER JOIN ENTIDADE ENTLOCAL
    ON ENTLOCAL.ENTIDADE = RELLOCAL.PAPEL1

INNER JOIN RELACAOENTIDADE RELCLI
    ON RELCLI.RELACAOENTIDADE = RELLOCAL.PAPEL2

INNER JOIN ENTIDADE ENTCLI
    ON ENTCLI.ENTIDADE = RELCLI.PAPEL1

LEFT JOIN LIGAPOSTOLOCALAREASUPER LIGA
    ON LIGA.POSTOLOCALSERVICO = POSTOLOCALSERVICO.POSTOLOCALSERVICO
   AND LIGA.TURNOTRABALHO = VAGA.TURNOTRABALHO
   AND LIGA.SITUACAO = 1

LEFT JOIN RELACAOENTIDADE RELAREA
    ON RELAREA.RELACAOENTIDADE = LIGA.AREASUPERVISAO

LEFT JOIN ENTIDADE ENTAREA
    ON ENTAREA.ENTIDADE = RELAREA.PAPEL1

WHERE
    PONTO.SITMOBRAHOJE = 9
    AND COALESCE(PONTO.TPABONOPONTO, 1) IN (1,2,3)

/* =========================
   SUSPENSÃO
========================= */
UNION ALL

SELECT
    PONTO.DATA AS DATA,
    RELFUNC.CODIGO AS RE,
    ENTFUNC.NOMERESUMIDO AS FUNCIONARIO,

    'SUSPENSAO' AS TIPO_EVENTO,

    ENTEMP.NOMERESUMIDO AS EMPRESA,
    ENTBASE.NOMERESUMIDO AS BASEOPERACIONAL,
    ENTCLI.NOMERESUMIDO AS CLIENTE,
    ENTLOCAL.NOMERESUMIDO AS LOCALSERVICO,
    ENTAREA.NOMECOMPLETO AS AREASUPERVISAO,
    TURNOTRABALHO.DESCRICAO AS TURNO,
    CARGO.DESCRICAO AS CARGO

FROM SITMAODEOBRAFUNC

INNER JOIN FUNCIONARIO
    ON FUNCIONARIO.FUNCIONARIO = SITMAODEOBRAFUNC.FUNCIONARIO

INNER JOIN RELFUNC_FIX RELFUNC
    ON RELFUNC.RELACAOENTIDADE = FUNCIONARIO.FUNCIONARIO

INNER JOIN ENTIDADE ENTFUNC
    ON ENTFUNC.ENTIDADE = RELFUNC.PAPEL1

INNER JOIN PONTO
    ON PONTO.COLABORADOR = SITMAODEOBRAFUNC.FUNCIONARIO
   AND PONTO.DATA BETWEEN SITMAODEOBRAFUNC.DTINICIO
   AND COALESCE(SITMAODEOBRAFUNC.DTFIM, GETDATE())

OUTER APPLY (
    SELECT TOP 1 CF.*
    FROM CARGOFUNCIONARIOS CF
    WHERE CF.FUNCIONARIO = FUNCIONARIO.FUNCIONARIO
      AND CF.DTINICIO <= PONTO.DATA
      AND (CF.DTFIM >= PONTO.DATA OR CF.DTFIM IS NULL)
    ORDER BY CF.DTINICIO DESC
) CF_REF

INNER JOIN CARGO
    ON CF_REF.CARGO = CARGO.CARGO

INNER JOIN VAGAITEMCONTRATO VAGA
    ON VAGA.VAGAITEMCONTRATO = PONTO.VAGAITEMCONTRATO

INNER JOIN TURNOTRABALHO
    ON VAGA.TURNOTRABALHO = TURNOTRABALHO.TURNOTRABALHO

INNER JOIN POSTOLOCALSERVICO
    ON POSTOLOCALSERVICO.POSTOLOCALSERVICO = VAGA.POSTOLOCALSERVICO

INNER JOIN LOCALSERVICOEMP
    ON LOCALSERVICOEMP.LOCALSERVICOEMP = POSTOLOCALSERVICO.LOCALSERVICOEMP

INNER JOIN RELACAOENTIDADE RELEMP
    ON RELEMP.RELACAOENTIDADE = LOCALSERVICOEMP.EMPRESA

INNER JOIN ENTIDADE ENTEMP
    ON ENTEMP.ENTIDADE = RELEMP.PAPEL1

INNER JOIN LOCALSERVICO
    ON LOCALSERVICO.LOCALSERVICO = LOCALSERVICOEMP.LOCALSERVICO

INNER JOIN RELACAOENTIDADE RELBASE
    ON RELBASE.RELACAOENTIDADE = LOCALSERVICO.BASEOPERACIONAL

INNER JOIN ENTIDADE ENTBASE
    ON ENTBASE.ENTIDADE = RELBASE.PAPEL1

INNER JOIN RELACAOENTIDADE RELLOCAL
    ON RELLOCAL.RELACAOENTIDADE = LOCALSERVICOEMP.LOCALSERVICO

INNER JOIN ENTIDADE ENTLOCAL
    ON ENTLOCAL.ENTIDADE = RELLOCAL.PAPEL1

INNER JOIN RELACAOENTIDADE RELCLI
    ON RELCLI.RELACAOENTIDADE = RELLOCAL.PAPEL2

INNER JOIN ENTIDADE ENTCLI
    ON ENTCLI.ENTIDADE = RELCLI.PAPEL1

LEFT JOIN LIGAPOSTOLOCALAREASUPER LIGA
    ON LIGA.POSTOLOCALSERVICO = POSTOLOCALSERVICO.POSTOLOCALSERVICO
   AND LIGA.TURNOTRABALHO = VAGA.TURNOTRABALHO
   AND LIGA.SITUACAO = 1

LEFT JOIN RELACAOENTIDADE RELAREA
    ON RELAREA.RELACAOENTIDADE = LIGA.AREASUPERVISAO

LEFT JOIN ENTIDADE ENTAREA
    ON ENTAREA.ENTIDADE = RELAREA.PAPEL1

WHERE
    SITMAODEOBRAFUNC.SITUACAOMOBRATEMP = 7
    AND SITMAODEOBRAFUNC.SITUACAO = 1

/* =========================
   ADVERTÊNCIA
========================= */
UNION ALL

SELECT
    HD.DTINICIOOCORRENCIA AS DATA,
    RELFUNC.CODIGO AS RE,
    ENTFUNC.NOMERESUMIDO AS FUNCIONARIO,

    CASE
        WHEN PP.DESCRICAO LIKE '%VERBAL%' THEN 'ADVERTENCIA VERBAL'
        WHEN PP.DESCRICAO LIKE '%ESCRITA%' THEN 'ADVERTENCIA ESCRITA'
        ELSE 'ADVERTENCIA'
    END AS TIPO_EVENTO,

    ENTEMP.NOMERESUMIDO AS EMPRESA,
    ENTBASE.NOMERESUMIDO AS BASEOPERACIONAL,
    ENTCLI.NOMERESUMIDO AS CLIENTE,
    ENTLOCAL.NOMERESUMIDO AS LOCALSERVICO,
    ENTAREA.NOMECOMPLETO AS AREASUPERVISAO,
    TURNOTRABALHO.DESCRICAO AS TURNO,
    CARGO.DESCRICAO AS CARGO

FROM HISTDISCIPLINAR HD
JOIN POLITICAPUNICAO PP
    ON PP.POLITICAPUNICAO = HD.POLITICAPUNICAO
JOIN FUNCIONARIO F
    ON F.FUNCIONARIO = HD.COLABORADOR
JOIN RELFUNC_FIX RELFUNC
    ON RELFUNC.RELACAOENTIDADE = F.FUNCIONARIO
JOIN ENTIDADE ENTFUNC
    ON ENTFUNC.ENTIDADE = RELFUNC.PAPEL1

OUTER APPLY (
    SELECT TOP 1 P.*
    FROM PONTO P
    WHERE P.COLABORADOR = HD.COLABORADOR
      AND P.DATA <= HD.DTINICIOOCORRENCIA
    ORDER BY P.DATA DESC
) PONTO_REF

LEFT JOIN VAGAITEMCONTRATO VAGA
    ON VAGA.VAGAITEMCONTRATO = PONTO_REF.VAGAITEMCONTRATO
LEFT JOIN TURNOTRABALHO
    ON TURNOTRABALHO.TURNOTRABALHO = VAGA.TURNOTRABALHO
LEFT JOIN POSTOLOCALSERVICO
    ON POSTOLOCALSERVICO.POSTOLOCALSERVICO = VAGA.POSTOLOCALSERVICO
LEFT JOIN LOCALSERVICOEMP
    ON LOCALSERVICOEMP.LOCALSERVICOEMP = POSTOLOCALSERVICO.LOCALSERVICOEMP
LEFT JOIN RELACAOENTIDADE RELEMP
    ON RELEMP.RELACAOENTIDADE = F.EMPRESA
LEFT JOIN ENTIDADE ENTEMP
    ON ENTEMP.ENTIDADE = RELEMP.PAPEL1
LEFT JOIN RELACAOENTIDADE RELBASE
    ON RELBASE.RELACAOENTIDADE = VAGA.BASEOPERACIONAL
LEFT JOIN ENTIDADE ENTBASE
    ON ENTBASE.ENTIDADE = RELBASE.PAPEL1
LEFT JOIN RELACAOENTIDADE RELLOCAL
    ON RELLOCAL.RELACAOENTIDADE = VAGA.LOCALSERVICO
LEFT JOIN ENTIDADE ENTLOCAL
    ON ENTLOCAL.ENTIDADE = RELLOCAL.PAPEL1
LEFT JOIN RELACAOENTIDADE RELCLI
    ON RELCLI.RELACAOENTIDADE = VAGA.CLIENTE
LEFT JOIN ENTIDADE ENTCLI
    ON ENTCLI.ENTIDADE = RELCLI.PAPEL1

LEFT JOIN LIGAPOSTOLOCALAREASUPER LIGA
    ON LIGA.POSTOLOCALSERVICO = POSTOLOCALSERVICO.POSTOLOCALSERVICO
   AND LIGA.TURNOTRABALHO = VAGA.TURNOTRABALHO
   AND LIGA.SITUACAO = 1

LEFT JOIN RELACAOENTIDADE RELAREA
    ON RELAREA.RELACAOENTIDADE = LIGA.AREASUPERVISAO
LEFT JOIN ENTIDADE ENTAREA
    ON ENTAREA.ENTIDADE = RELAREA.PAPEL1

OUTER APPLY (
    SELECT TOP 1 CF.*
    FROM CARGOFUNCIONARIOS CF
    WHERE CF.FUNCIONARIO = F.FUNCIONARIO
      AND CF.DTINICIO <= HD.DTINICIOOCORRENCIA
      AND (CF.DTFIM >= HD.DTINICIOOCORRENCIA OR CF.DTFIM IS NULL)
    ORDER BY CF.DTINICIO DESC
) CF_REF

LEFT JOIN CARGO
    ON CARGO.CARGO = CF_REF.CARGO

WHERE PP.DESCRICAO LIKE '%ADVERTENCIA%'
)

SELECT * FROM BASE_EVENTOS;
"""

# ===============================
# GOOGLE SHEETS
# ===============================


def conectar_sheets():
    scopes = ["https://www.googleapis.com/auth/spreadsheets"]
    creds = Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=scopes)
    return gspread.authorize(creds)

# ===============================
# FUNÇÃO DE LOG NO SHEETS
# ===============================


def atualizar_log_sheets(status, mensagem):
    try:
        gc = conectar_sheets()
        sh = gc.open_by_key(LOG_SPREADSHEET_ID)

        try:
            ws = sh.worksheet(LOG_WORKSHEET_NAME)
        except gspread.exceptions.WorksheetNotFound:
            ws = sh.add_worksheet(title=LOG_WORKSHEET_NAME, rows=1000, cols=5)
            ws.update("A1", [["DATA", "STATUS", "MENSAGEM"]])

        agora = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
        ws.append_row([agora, status, mensagem])

    except Exception as e:
        logging.error("Erro ao atualizar planilha de log", exc_info=True)
        print("Erro ao atualizar planilha de log:", e)
        raise

# ===============================
# MAIN
# ===============================


def main():
    atualizar_log_sheets("INICIO", "Processo iniciado")
    try:
        logging.info("Iniciando processo")
        print("🔌 Conectando no SQL Server...")

        # 🔐 Conexão segura (fecha automaticamente)
        with conectar_bd() as conn:
            print("📥 Executando query...")
            df = pd.read_sql(QUERY, conn)

        logging.info(f"Registros retornados: {len(df)}")
        print(f"📊 Registros retornados: {len(df)}")

        # Converte datetime para string
        for col in df.select_dtypes(include=["datetime64[ns]"]).columns:
            df[col] = df[col].dt.strftime("%Y-%m-%d %H:%M:%S")

        # Remove NaN e Inf
        df = df.replace([np.inf, -np.inf], "")
        df = df.fillna("")
        df = df.astype(str)

        print("📄 Conectando no Google Sheets...")
        gc = conectar_sheets()
        sh = gc.open_by_key(SPREADSHEET_ID)

        try:
            ws = sh.worksheet(WORKSHEET_NAME)
        except gspread.exceptions.WorksheetNotFound:
            ws = sh.add_worksheet(title=WORKSHEET_NAME, rows=1000, cols=df.shape[1]+2)  # noqa: E501
            ws.update("A1", [df.columns.tolist()])

        existing_rows = len(ws.get_all_values())

        # Batch clear dinâmico
        last_col = chr(65 + df.shape[1] - 1)  # Coluna final baseado no DF
        if existing_rows > 1:
            ws.batch_clear([f"A2:{last_col}{existing_rows}"])

        # Atualiza dados
        ws.update("A2", df.values.tolist())

        logging.info("Job finalizado com sucesso")
        print("✅ Planilha atualizada com sucesso!")

        atualizar_log_sheets("SUCESSO", f"{len(df)} registros processados")

    except Exception as e:
        logging.error("Erro fatal na execução do job", exc_info=True)
        atualizar_log_sheets("ERRO", f"Falha na execução: {e}")
        print("❌ Erro na execução. Verifique o log.")
        raise  # garante que o Healthcheck veja falha

# ===============================
# EXECUÇÃO MONITORADA
# ===============================


PING_URL = "https://hc-ping.com/015aa040-0de1-4bb2-b51b-57984c727657"

if __name__ == "__main__":
    run_with_monitor(main, PING_URL)
